# Generated by Django 3.0.5 on 2020-05-05 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20200309_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='site_avatar',
            field=models.CharField(default='http://imagesoda.oss-cn-beijing.aliyuncs.com/Sodaoo/2020-05-05-WechatIMG54.jpeg', max_length=200, verbose_name='我的头像'),
        ),
    ]
